import type { Provincia } from "@prisma/client";

/**
 * Localidades de Argentina agrupadas por provincia, para el <select>
 * dependiente de /listings/new y del filtro de /listings — evita que el
 * dropdown arranque vacío hasta que haya publicaciones reales.
 *
 * Fuente: API oficial de Georef (georef.gob.ar / apis.datos.gob.ar),
 * endpoint /municipios — son los municipios/partidos con gobierno local
 * real, no la granularidad de "localidad censal" (que incluye cada
 * paraje/colonia rural y hubiera hecho el filtro inmanejable). Excepciones:
 *   - CABA: no tiene municipios, así que se usan sus 48 barrios oficiales.
 *   - Santa Cruz y Santiago del Estero: el endpoint de municipios no
 *     devuelve nada para estas dos, se usó /localidades en su lugar.
 */
export const LOCALIDADES_ARGENTINA: Record<Provincia, string[]> = {
  CABA: [
    "Agronomía",
    "Almagro",
    "Balvanera",
    "Barracas",
    "Belgrano",
    "Boedo",
    "Caballito",
    "Chacarita",
    "Coghlan",
    "Colegiales",
    "Constitución",
    "Flores",
    "Floresta",
    "La Boca",
    "La Paternal",
    "Liniers",
    "Mataderos",
    "Monserrat",
    "Monte Castro",
    "Nueva Pompeya",
    "Núñez",
    "Palermo",
    "Parque Avellaneda",
    "Parque Chacabuco",
    "Parque Chas",
    "Parque Patricios",
    "Puerto Madero",
    "Recoleta",
    "Retiro",
    "Saavedra",
    "San Cristóbal",
    "San Nicolás",
    "San Telmo",
    "Vélez Sarsfield",
    "Versalles",
    "Villa Crespo",
    "Villa del Parque",
    "Villa Devoto",
    "Villa General Mitre",
    "Villa Lugano",
    "Villa Luro",
    "Villa Ortúzar",
    "Villa Pueyrredón",
    "Villa Real",
    "Villa Riachuelo",
    "Villa Santa Rita",
    "Villa Soldati",
    "Villa Urquiza",
  ],
  BUENOS_AIRES: [
    "25 de Mayo",
    "9 de Julio",
    "Adolfo Alsina",
    "Adolfo Gonzales Chaves",
    "Alberti",
    "Almirante Brown",
    "Arrecifes",
    "Avellaneda",
    "Ayacucho",
    "Azul",
    "Bahía Blanca",
    "Balcarce",
    "Baradero",
    "Benito Juárez",
    "Berazategui",
    "Berisso",
    "Bolívar",
    "Bragado",
    "Brandsen",
    "Campana",
    "Cañuelas",
    "Capitán Sarmiento",
    "Carlos Casares",
    "Carlos Tejedor",
    "Carmen de Areco",
    "Castelli",
    "Chacabuco",
    "Chascomús",
    "Chivilcoy",
    "Colón",
    "Coronel de Marina Leonardo Rosales",
    "Coronel Dorrego",
    "Coronel Pringles",
    "Coronel Suárez",
    "Daireaux",
    "Dolores",
    "Ensenada",
    "Escobar",
    "Esteban Echeverría",
    "Exaltación de la Cruz",
    "Ezeiza",
    "Florencio Varela",
    "Florentino Ameghino",
    "General Alvarado",
    "General Alvear",
    "General Arenales",
    "General Belgrano",
    "General Guido",
    "General Juan Madariaga",
    "General La Madrid",
    "General Las Heras",
    "General Lavalle",
    "General Paz",
    "General Pinto",
    "General Pueyrredón",
    "General Rodríguez",
    "General San Martín",
    "General Viamonte",
    "General Villegas",
    "Guaminí",
    "Hipólito Yrigoyen",
    "Hurlingham",
    "Ituzaingó",
    "José C. Paz",
    "Junín",
    "La Costa",
    "La Matanza",
    "La Plata",
    "Lanús",
    "Laprida",
    "Las Flores",
    "Leandro N. Alem",
    "Lezama",
    "Lincoln",
    "Lobería",
    "Lobos",
    "Lomas de Zamora",
    "Luján",
    "Magdalena",
    "Maipú",
    "Malvinas Argentinas",
    "Mar Chiquita",
    "Marcos Paz",
    "Mercedes",
    "Merlo",
    "Monte",
    "Monte Hermoso",
    "Moreno",
    "Morón",
    "Navarro",
    "Necochea",
    "Olavarría",
    "Patagones",
    "Pehuajó",
    "Pellegrini",
    "Pergamino",
    "Pila",
    "Pilar",
    "Pinamar",
    "Presidente Perón",
    "Puán",
    "Punta Indio",
    "Quilmes",
    "Ramallo",
    "Rauch",
    "Rivadavia",
    "Rojas",
    "Roque Pérez",
    "Saavedra",
    "Saladillo",
    "Salliqueló",
    "Salto",
    "San Andrés de Giles",
    "San Antonio de Areco",
    "San Cayetano",
    "San Fernando",
    "San Isidro",
    "San Miguel",
    "San Nicolás",
    "San Pedro",
    "San Vicente",
    "Suipacha",
    "Tandil",
    "Tapalqué",
    "Tigre",
    "Tordillo",
    "Tornquist",
    "Trenque Lauquen",
    "Tres Arroyos",
    "Tres de Febrero",
    "Tres Lomas",
    "Vicente López",
    "Villa Gesell",
    "Villarino",
    "Zárate",
  ],
  CATAMARCA: [
    "Aconquija",
    "Ancasti",
    "Andalgalá",
    "Antofagasta de la Sierra",
    "Belén",
    "Capayán",
    "Corral Quemado",
    "El Alto",
    "El Rodeo",
    "Fiambalá",
    "Fray Mamerto Esquiú",
    "Hualfin",
    "Huillapima",
    "Icaño",
    "La Puerta",
    "Las Juntas",
    "Londres",
    "Los Altos",
    "Los Varela",
    "Mutquin",
    "Paclín",
    "Pomán",
    "Pozo de Piedra",
    "Puerta de Corral Quemado",
    "Puerta de San José",
    "Recreo",
    "San Fernando",
    "San Fernando del Valle de Catamarca",
    "San José",
    "Santa María",
    "Santa Rosa",
    "Saujil",
    "Tapso",
    "Tinogasta",
    "Valle Viejo",
    "Villa Vil",
  ],
  CHACO: [
    "Avia Terai",
    "Barranqueras",
    "Basail",
    "Campo Largo",
    "Capitán Solari",
    "Charadai",
    "Charata",
    "Chorotis",
    "Ciervo Petiso",
    "Colonia Benítez",
    "Colonia Elisa",
    "Colonia Popular",
    "Colonias Unidas",
    "Concepción del Bermejo",
    "Coronel Du Graty",
    "Corzuela",
    "Cote Lai",
    "El Sauzalito",
    "Enrique Urién",
    "Fontana",
    "Fuerte Esperanza",
    "Gancedo",
    "General Capdevila",
    "General Pinedo",
    "General San Martín",
    "General Vedia",
    "Hermoso Campo",
    "Isla del Cerrito",
    "Juan José Castelli",
    "La Clotilde",
    "La Eduvigis",
    "La Escondida",
    "La Leonesa",
    "La Tigra",
    "La Verde",
    "Laguna Blanca",
    "Laguna Limpia",
    "Lapachito",
    "Las Breñas",
    "Las Garcitas",
    "Las Palmas",
    "Los Frentones",
    "Machagai",
    "Makallé",
    "Margarita Belén",
    "Miraflores",
    "Misión Nueva Pompeya",
    "Napenay",
    "Pampa Almirón",
    "Pampa del Indio",
    "Pampa del Infierno",
    "Presidencia de la Plaza",
    "Presidencia Roca",
    "Presidencia Roque Sáenz Peña",
    "Puerto Bermejo",
    "Puerto Eva Perón",
    "Puerto Tirol",
    "Puerto Vilelas",
    "Quitilipi",
    "Resistencia",
    "Samuhú",
    "San Bernardo",
    "Santa Sylvina",
    "Taco Pozo",
    "Tres Isletas",
    "Villa Ángela",
    "Villa Berthet",
    "Villa Río Bermejito",
  ],
  CHUBUT: [
    "28 de Julio",
    "Aldea Beleiro",
    "Aldea Epulef",
    "Alto Río Senguer",
    "Buen Pasto",
    "Camarones",
    "Carrenleufú",
    "Cerro Centinela",
    "Cholila",
    "Colan Conhue",
    "Comodoro Rivadavia",
    "Corcovado",
    "Cushamen",
    "Dique Florentino Ameghino",
    "Doctor Ricardo Rojas",
    "Dolavon",
    "Dr. Atilio Oscar Viglione",
    "El Hoyo",
    "El Maitén",
    "Epuyén",
    "Esquel",
    "Facundo",
    "Gaiman",
    "Gan Gan",
    "Gastre",
    "Gobernador Costa",
    "Gualjaina",
    "José de San Martín",
    "Lago Blanco",
    "Lago Puelo",
    "Lagunita Salada",
    "Las Plumas",
    "Los Altares",
    "Paso de Indios",
    "Paso del Sapo",
    "Puerto Madryn",
    "Puerto Pirámides",
    "Rada Tilly",
    "Rawson",
    "Río Mayo",
    "Río Pico",
    "Sarmiento",
    "Tecka",
    "Telsen",
    "Trelew",
    "Trevelin",
  ],
  CORDOBA: [
    "Achiras",
    "Adelia María",
    "Agua de Oro",
    "Alcira",
    "Aldea Santa María",
    "Alejandro Roca",
    "Alejo Ledesma",
    "Alicia",
    "Almafuerte",
    "Alpa Corral",
    "Alta Gracia",
    "Alto Alegre",
    "Alto de los Quebrachos",
    "Altos de Chipión",
    "Amboy",
    "Ambul",
    "Ana Zumarán",
    "Anisacate",
    "Arias",
    "Arroyito",
    "Arroyo Algodón",
    "Arroyo Cabral",
    "Arroyo de los Patos",
    "Assunta",
    "Atahona",
    "Ausonia",
    "Avellaneda",
    "Ballesteros",
    "Ballesteros Sud",
    "Balnearia",
    "Bañado de Soto",
    "Bell Ville",
    "Bengolea",
    "Benjamín Gould",
    "Berrotarán",
    "Bialet Massé",
    "Bouwer",
    "Brinkmann",
    "Buchardo",
    "Bulnes",
    "Cabalango",
    "Calchín",
    "Calchín Oeste",
    "Camilo Aldao",
    "Caminiaga",
    "Canals",
    "Candelaria Sud",
    "Cañada de Luque",
    "Cañada de Machado",
    "Cañada de Río Pinto",
    "Cañada del Sauce",
    "Capilla de los Remedios",
    "Capilla de Sitón",
    "Capilla del Carmen",
    "Capilla del Monte",
    "Capitán General Bernardo O'Higgins",
    "Carnerillo",
    "Carrilobo",
    "Casa Grande",
    "Cavanagh",
    "Cerro Colorado",
    "Chaján",
    "Chalacea",
    "Chancani",
    "Chañar Viejo",
    "Charbonier",
    "Charras",
    "Chazón",
    "Chilibroste",
    "Chucul",
    "Chuña",
    "Chuña Huasi",
    "Churqui Cañada",
    "Ciénaga del Coro",
    "Cintra",
    "Colazo",
    "Colonia Almada",
    "Colonia Anita",
    "Colonia Barge",
    "Colonia Bismarck",
    "Colonia Bremen",
    "Colonia Caroya",
    "Colonia Italiana",
    "Colonia Iturraspe",
    "Colonia Las Cuatro Esquinas",
    "Colonia Las Pichanas",
    "Colonia Marina",
    "Colonia Prosperidad",
    "Colonia San Bartolomé",
    "Colonia San Pedro",
    "Colonia Tirolesa",
    "Colonia Valtelina",
    "Colonia Vicente Agüero",
    "Colonia Videla",
    "Colonia Vignaud",
    "Comechingones",
    "Conlara",
    "Copacabana",
    "Córdoba",
    "Coronel Baigorria",
    "Coronel Moldes",
    "Corral de Bustos Ifflinger",
    "Corralito",
    "Cosquín",
    "Costa Sacate",
    "Cruz Alta",
    "Cruz de Caña",
    "Cruz del Eje",
    "Cuesta Blanca",
    "Dalmacio Vélez",
    "Deán Funes",
    "Del Campillo",
    "Despeñaderos",
    "Devoto",
    "Diego de Rojas",
    "Dique Chico",
    "El Arañado",
    "El Brete",
    "El Chacho",
    "El Crispín",
    "El Fortín",
    "El Manzano",
    "El Rastreador",
    "El Rodeo",
    "El Tío",
    "Elena",
    "Embalse",
    "Esquina",
    "Estación General Paz",
    "Estación Juárez Celman",
    "Estancia de Guadalupe",
    "Estancia Vieja",
    "Etruria",
    "Eufrasio Loza",
    "Falda del Carmen",
    "Freyre",
    "General Baldissera",
    "General Cabrera",
    "General Deheza",
    "General Fotheringham",
    "General Levalle",
    "General Roca",
    "Guanaco Muerto",
    "Guasapampa",
    "Guatimozín",
    "Gutemberg",
    "Hernando",
    "Huanchilla",
    "Huerta Grande",
    "Huinca Renancó",
    "Idiazábal",
    "Impira",
    "Inriville",
    "Isla Verde",
    "Italó",
    "James Craik",
    "Jesús María",
    "Jovita",
    "Justiniano Posse",
    "Kilómetro 658",
    "La Batea",
    "La Calera",
    "La Carlota",
    "La Carolina El Potosí",
    "La Cautiva",
    "La Cesira",
    "La Cruz",
    "La Cumbre",
    "La Cumbrecita",
    "La Falda",
    "La Francia",
    "La Granja",
    "La Higuera",
    "La Laguna",
    "La Paisanita",
    "La Palestina",
    "La Pampa",
    "La Paquita",
    "La Para",
    "La Paz",
    "La Playa",
    "La Playosa",
    "La Población",
    "La Posta",
    "La Puerta",
    "La Quinta",
    "La Rancherita",
    "La Rinconada",
    "La Serranita",
    "La Tordilla",
    "Laborde",
    "Laboulaye",
    "Laguna Larga",
    "Las Acequias",
    "Las Albahacas",
    "Las Arrias",
    "Las Bajadas",
    "Las Caleras",
    "Las Calles",
    "Las Cañadas",
    "Las Gramillas",
    "Las Higueras",
    "Las Isletillas",
    "Las Junturas",
    "Las Palmas",
    "Las Peñas",
    "Las Peñas Sud",
    "Las Perdices",
    "Las Playas",
    "Las Rabonas",
    "Las Saladas",
    "Las Tapias",
    "Las Varas",
    "Las Varillas",
    "Las Vertientes",
    "Leguizamón",
    "Leones",
    "Los Cedros",
    "Los Cerrillos",
    "Los Chañaritos",
    "Los Cisnes",
    "Los Cocos",
    "Los Cóndores",
    "Los Hornillos",
    "Los Hoyos",
    "Los Mistoles",
    "Los Molinos",
    "Los Pozos",
    "Los Reartes",
    "Los Surgentes",
    "Los Talares",
    "Los Zorros",
    "Lozada",
    "Luca",
    "Lucio Victorio Mansilla",
    "Luque",
    "Lutti",
    "Luyaba",
    "Malagueño",
    "Malena",
    "Malvinas Argentinas",
    "Manfredi",
    "Maquinista Gallini",
    "Marcos Juárez",
    "Marull",
    "Matorrales",
    "Mattaldi",
    "Mayu Sumaj",
    "Media Naranja",
    "Melo",
    "Mendiolaza",
    "Mi Granja",
    "Mina Clavero",
    "Miramar de Ansenuza",
    "Monte Buey",
    "Monte de los Gauchos",
    "Monte Leña",
    "Monte Maíz",
    "Monte Ralo",
    "Montecristo",
    "Morrison",
    "Morteros",
    "Nicolás Bruzzone",
    "Noetinger",
    "Nono",
    "Obispo Trejo",
    "Olaeta",
    "Oliva",
    "Olivares de San Nicolás",
    "Onagoity",
    "Oncativo",
    "Ordóñez",
    "Pacheco de Melo",
    "Pampayasta Norte",
    "Pampayasta Sud",
    "Panaholma",
    "Parque Calmayo",
    "Pascanas",
    "Pasco",
    "Paso del Durazno",
    "Paso Viejo",
    "Pilar",
    "Pincén",
    "Piquillín",
    "Plaza de Mercedes",
    "Plaza Luxardo",
    "Porteña",
    "Potrero de Garay",
    "Pozo del Molle",
    "Pozo Nuevo",
    "Pueblo Italiano",
    "Puesto de Castro",
    "Punta del Agua",
    "Quebracho Herrado",
    "Quilino",
    "Rafael García",
    "Ranqueles",
    "Rayo Cortado",
    "Reducción",
    "Rincón",
    "Río Bamba",
    "Río Ceballos",
    "Río Cuarto",
    "Río de los Sauces",
    "Río Primero",
    "Río Segundo",
    "Río Tercero",
    "Rosales",
    "Rosario del Saladillo",
    "Sacanta",
    "Sagrada Familia",
    "Saira",
    "Saladillo",
    "Saldán",
    "Salsacate",
    "Salsipuedes",
    "Sampacho",
    "San Agustín",
    "San Antonio de Arredondo",
    "San Antonio de Litín",
    "San Basilio",
    "San Carlos Minas",
    "San Clemente",
    "San Esteban",
    "San Francisco",
    "San Francisco del Chañar",
    "San Gerónimo",
    "San Ignacio",
    "San Javier y Yacanto",
    "San Joaquín",
    "San José",
    "San José de la Dormida",
    "San José de las Salinas",
    "San Lorenzo",
    "San Marcos Sierra",
    "San Marcos Sud",
    "San Pedro",
    "San Pedro Norte",
    "San Roque",
    "San Vicente",
    "Santa Catalina Holmberg",
    "Santa Elena",
    "Santa Eufemia",
    "Santa María de Punilla",
    "Santa Rosa de Calamuchita",
    "Santiago Temple",
    "Sarmiento",
    "Saturnino María Laspiur",
    "Sauce Arriba",
    "Sebastián Elcano",
    "Seeber",
    "Segunda Usina",
    "Serrano",
    "Serrezuela",
    "Silvio Pellico",
    "Simbolar",
    "Sinsacate",
    "Suco",
    "Tala Cañada",
    "Tala Huasi",
    "Talaini",
    "Tancacha",
    "Tanti",
    "Ticino",
    "Tinoco",
    "Tío Pujio",
    "Toledo",
    "Toro Pujio",
    "Tosno",
    "Tosquita",
    "Tránsito",
    "Tuclame",
    "Ucacha",
    "Unquillo",
    "Valle de Anisacate",
    "Valle Hermoso",
    "Viamonte",
    "Vicuña Mackenna",
    "Villa Allende",
    "Villa Amancay",
    "Villa Ascasubi",
    "Villa Candelaria Norte",
    "Villa Carlos Paz",
    "Villa Cerro Azul",
    "Villa Ciudad de América",
    "Villa Ciudad Parque Los Reartes",
    "Villa Concepción del Tío",
    "Villa Cura Brochero",
    "Villa de las Rosas",
    "Villa de María",
    "Villa de Pocho",
    "Villa de Soto",
    "Villa del Dique",
    "Villa del Prado",
    "Villa del Rosario",
    "Villa del Totoral",
    "Villa Dolores",
    "Villa El Chacay",
    "Villa Elisa",
    "Villa Fontana",
    "Villa General Belgrano",
    "Villa Giardino",
    "Villa Gutiérrez",
    "Villa Huidobro",
    "Villa La Bolsa",
    "Villa Los Aromos",
    "Villa Los Patos",
    "Villa María",
    "Villa Nueva",
    "Villa Parque Santa Ana",
    "Villa Parque Síquiman",
    "Villa Quillinzo",
    "Villa Río Icho Cruz",
    "Villa Rossi",
    "Villa Rumipal",
    "Villa San Esteban",
    "Villa San Isidro",
    "Villa Santa Cruz del Lago",
    "Villa Santa Rosa",
    "Villa Sarmiento",
    "Villa Tulumba",
    "Villa Valeria",
    "Villa Yacanto",
    "Washington",
    "Wenceslao Escalante",
  ],
  CORRIENTES: [
    "9 de Julio",
    "Alvear",
    "Bella Vista",
    "Bonpland",
    "Caá Catí",
    "Carolina",
    "Cazadores Correntinos",
    "Cecilio Echavarría",
    "Chavarría",
    "Colonia Carlos Pellegrini",
    "Colonia Libertad",
    "Colonia Liebig",
    "Colonia Pando",
    "Colonia Santa Rosa",
    "Concepción del Yaguareté Corá",
    "Corrientes",
    "Cruz de los Milagros",
    "Curuzú Cuatiá",
    "El Sombrero",
    "Empedrado",
    "Esquina",
    "Estación Torrent",
    "Felipe Yofré",
    "Garaví",
    "Garruchos",
    "Gobernador Martínez",
    "Gobernador Virasoro",
    "Goya",
    "Guaviraví",
    "Herlitzka",
    "Itá Ibaté",
    "Itatí",
    "Ituzaingó",
    "Juan Pujol",
    "La Cruz",
    "Lavalle",
    "Lomas de Vallejos",
    "Loreto",
    "Mariano I. Loza",
    "Mburucuyá",
    "Mercedes",
    "Mocoretá",
    "Monte Caseros",
    "Pago de los Deseos",
    "Palmar Grande",
    "Parada Pucheta",
    "Paso de la Patria",
    "Paso de los Libres",
    "Pedro R. Fernández",
    "Perugorría",
    "Pueblo Libertador",
    "Ramada Paso",
    "Riachuelo",
    "Saladas",
    "San Antonio de Itatí",
    "San Antonio Isla Apipé Grande",
    "San Carlos",
    "San Cosme",
    "San Isidro",
    "San Lorenzo",
    "San Luis del Palmar",
    "San Miguel",
    "San Roque",
    "Santa Ana de los Guácaras",
    "Santa Lucía",
    "Santo Tomé",
    "Sauce",
    "Tabay",
    "Tapebicuá",
    "Tatacuá",
    "Tres de Abril",
    "Villa Olivari",
    "Yapeyú",
    "Yatay Ti Calle",
  ],
  ENTRE_RIOS: [
    "1º de Mayo",
    "Alcaraz",
    "Alcaraz Norte",
    "Alcaraz Sur",
    "Aldea Asunción",
    "Aldea Brasilera",
    "Aldea Eigenfeld",
    "Aldea Grapschental",
    "Aldea Protestante",
    "Aldea Salto",
    "Aldea San Antonio",
    "Aldea San Juan",
    "Aldea San Miguel",
    "Aldea San Rafael",
    "Aldea Santa María",
    "Aldea Santa Rosa",
    "Aldea Spatzenkutter",
    "Aldea Valle María",
    "Altamirano Sur",
    "Antelo",
    "Antonio Tomás",
    "Arroyo Barú",
    "Arroyo Burgos",
    "Arroyo Cle",
    "Arroyo Corralito",
    "Arroyo del Medio",
    "Arroyo Gená",
    "Arroyo Las Tunas",
    "Arroyo Maturrango",
    "Arroyo Palo Seco",
    "Banderas",
    "Basavilbaso",
    "Betbeder",
    "Bovril",
    "Caseros",
    "Ceibas",
    "Cerrito",
    "Chajarí",
    "Chilcas",
    "Clodomiro Ledesma",
    "Colón",
    "Colonia Adivino",
    "Colonia Alemana",
    "Colonia Avellaneda",
    "Colonia Avigdor",
    "Colonia Ayuí",
    "Colonia Baylina",
    "Colonia Carrasco",
    "Colonia Celina",
    "Colonia Crespo",
    "Colonia Elía",
    "Colonia Ensayo",
    "Colonia La Argentina",
    "Colonia Merou",
    "Colonia Oficial N° 13",
    "Colonia Oficial Nº 3 y 14",
    "Colonia Oficial Nº 5",
    "Colonia San Anselmo y Aledañas",
    "Colonia Santa María y Las Margaritas",
    "Colonia Tunas",
    "Colonia Viraró",
    "Comuna Tala",
    "Concepción del Uruguay",
    "Concordia",
    "Conscripto Bernardi",
    "Costa Grande",
    "Costa San Antonio",
    "Costa Uruguay Norte",
    "Costa Uruguay Sur",
    "Crespo",
    "Crucesitas Octava",
    "Crucesitas Séptima",
    "Crucesitas Tercera",
    "Cuchilla Redonda",
    "Diamante",
    "Distrito Chañar",
    "Distrito Chiqueros",
    "Distrito Cuarto",
    "Distrito Diego López",
    "Distrito Pajonal",
    "Distrito Primero",
    "Distrito Quinto",
    "Distrito Sauce",
    "Distrito Sexto",
    "Distrito Tala",
    "Distrito Talitas",
    "Don Cristóbal I",
    "Don Cristóbal II",
    "Durazno",
    "El Cimarrón",
    "El Gramiyal",
    "El Palenque",
    "El Pingo",
    "El Quebracho",
    "El Redomón",
    "El Solar",
    "Enrique Carbó",
    "Espinillo Norte",
    "Estación Camps",
    "Estación Escriña",
    "Estación Lazo",
    "Estación Parera",
    "Estación Raíces",
    "Estación Sosa",
    "Estación Yeruá",
    "Estación Yuquerí",
    "Estancia Grande",
    "Estaquitas",
    "Febre",
    "Federación",
    "Federal",
    "General Almada",
    "General Alvear",
    "General Campos",
    "General Galarza",
    "General Ramírez",
    "General Roca",
    "Gilbert",
    "Gobernador Echagüe",
    "Gobernador Etchevehere",
    "Gobernador Mansilla",
    "Gobernador Racedo",
    "Gobernador Sola",
    "González Calderón",
    "Gualeguay",
    "Gualeguaycito",
    "Guardamonte",
    "Hambis",
    "Hasenkamp",
    "Hernandarias",
    "Herrera",
    "Hinojal",
    "Hocker",
    "Ibicuy",
    "Ingeniero Sajaroff",
    "Irazusta",
    "Isletas",
    "Jubileo",
    "Justo José de Urquiza",
    "La Clarita",
    "La Criolla",
    "La Esmeralda",
    "La Florida",
    "La Fraternidad y Santa Juana",
    "La Hierra",
    "La Ollita",
    "La Paz",
    "La Picada",
    "La Providencia",
    "La Verbena",
    "Laguna Benítez",
    "Laguna del Pescado",
    "Larroque",
    "Las Cuevas",
    "Las Garzas",
    "Las Guachas",
    "Las Mercedes",
    "Las Moscas",
    "Las Mulitas",
    "Las Toscas",
    "Laurencena",
    "Líbaros",
    "Loma Limpia",
    "Los Charrúas",
    "Los Conquistadores",
    "Lucas González",
    "Lucas Norte",
    "Lucas Sur Primero",
    "Lucas Sur Segundo",
    "Maciá",
    "María Grande",
    "María Grande 2º",
    "Maria Luisa",
    "Médanos",
    "Mojones Norte",
    "Mojones Sur",
    "Molino Doll",
    "Monte Redondo",
    "Montoya",
    "Mulas Grandes",
    "Nogoyá",
    "Nueva Escocia",
    "Nueva Vizcaya",
    "Ñancay",
    "Ombú",
    "Oro Verde",
    "Paraje Guayaquil",
    "Paraje Las Tunas",
    "Paraje Los Algarrobos",
    "Paraná",
    "Paso de la Arena",
    "Paso de La Laguna",
    "Paso de las Piedras",
    "Paso Duarte",
    "Pastor Britos",
    "Pedernal",
    "Perdices",
    "Picada Berón",
    "Piedras Blancas",
    "Pronunciamiento",
    "Pueblo Brugo",
    "Pueblo Cazes",
    "Pueblo General Belgrano",
    "Pueblo Liebig",
    "Puerto Algarrobo",
    "Puerto Curtiembre",
    "Puerto Yeruá",
    "Punta del Monte",
    "Quebracho",
    "Raíces Oeste",
    "Rincón de Nogoyá",
    "Rincón del Cinto",
    "Rincón del Doll",
    "Rincón del Gato",
    "Rocamora",
    "Rosario del Tala",
    "San Benito",
    "San Cipriano",
    "San Ernesto",
    "San Gustavo",
    "San Jaime de la Frontera",
    "San José",
    "San José de Feliciano",
    "San José de Gualeguaychú",
    "San Justo",
    "San Marcial",
    "San Miguel",
    "San Pedro",
    "San Ramírez",
    "San Ramón",
    "San Roque",
    "San Salvador",
    "San Víctor",
    "Santa Ana",
    "Santa Anita",
    "Santa Elena",
    "Santa Lucía",
    "Santa Luisa",
    "Sauce de Luna",
    "Sauce Montrull",
    "Sauce Pinto",
    "Sauce Sur",
    "Saucecito",
    "Seguí",
    "Sir Leonard",
    "Tabossi",
    "Tezanos Pinto",
    "Ubajay",
    "Urdinarrain",
    "Viale",
    "Victoria",
    "Villa Aranguren",
    "Villa Clara",
    "Villa del Rosario",
    "Villa Domínguez",
    "Villa Elisa",
    "Villa Fontana",
    "Villa Libertador San Martín",
    "Villa Mantero",
    "Villa Paranacito",
    "Villa Sabá Z. Hernández",
    "Villa Urquiza",
    "Villaguay",
    "Walter Moss",
    "XX de Septiembre",
    "Yacaré",
    "Yeso Oeste",
  ],
  FORMOSA: [
    "Buena Vista",
    "Clorinda",
    "Colonia Pastoril",
    "Comandante Fontana",
    "El Chorro",
    "El Colorado",
    "El Espinillo",
    "Estanislao del Campo",
    "Formosa",
    "Fortín Lugones",
    "General Lucio Victorio Mansilla",
    "General Manuel Belgrano",
    "Gran Guardia",
    "Herradura",
    "Ibarreta",
    "Ingeniero Guillermo Nicasio Juárez",
    "Laguna Blanca",
    "Laguna Naick Neck",
    "Laguna Yema",
    "Las Lomitas",
    "Los Chiriguanos",
    "Mayor Villafañe",
    "Misión San Francisco de Laishi",
    "Misión Tacaaglé",
    "Palo Santo",
    "Pirané",
    "Portón Negro",
    "Pozo del Tigre",
    "Riacho He He",
    "San Hilario",
    "San Martín Dos",
    "Siete Palmas",
    "Subteniente Perín",
    "Tres Lagunas",
    "Villa Dos Trece",
    "Villa Escolar",
    "Villa General Güemes",
  ],
  JUJUY: [
    "Abdón Castro Tolay",
    "Abra Pampa",
    "Abralaite",
    "Aguas Calientes",
    "Arrayanal",
    "Barrios",
    "Caimancito",
    "Calilegua",
    "Cangrejillos",
    "Caspalá",
    "Catua",
    "Cieneguillas",
    "Coranzuli",
    "Cusi Cusi",
    "El Aguilar",
    "El Carmen",
    "El Cóndor",
    "El Fuerte",
    "El Moreno",
    "El Piquete",
    "El Talar",
    "Fraile Pintado",
    "Hipólito Yrigoyen",
    "Huacalera",
    "Humahuaca",
    "La Esperanza",
    "La Mendieta",
    "La Quiaca",
    "Libertador General San Martín",
    "Maimará",
    "Mina Pirquitas",
    "Monterrico",
    "Palca de Aparzo",
    "Palma Sola",
    "Palpalá",
    "Pampa Blanca",
    "Pampichuela",
    "Perico",
    "Puesto del Marquez",
    "Puesto Viejo",
    "Pumahuasi",
    "Purmamarca",
    "Rinconada",
    "Rodeito",
    "Rosario de Río Grande",
    "San Antonio",
    "San Francisco",
    "San Pedro de Jujuy",
    "San Salvador de Jujuy",
    "Santa Ana",
    "Santa Catalina",
    "Santa Clara",
    "Susques",
    "Tilcara",
    "Tres Cruces",
    "Tumbaya",
    "Uquia",
    "Valle Grande",
    "Vinalito",
    "Volcán",
    "Yala",
    "Yavi",
    "Yuto",
  ],
  LA_PAMPA: [
    "Abramo",
    "Adolfo Van Praet",
    "Agustoni",
    "Algarrobo del Águila",
    "Alpachiri",
    "Alta Italia",
    "Anguil",
    "Arata",
    "Ataliva Roca",
    "Bernardo Larroudé",
    "Bernasconi",
    "Caleufú",
    "Carro Quemado",
    "Casa de Piedra",
    "Catriló",
    "Ceballos",
    "Chacharramendi",
    "Colonia 25 de Mayo",
    "Colonia Barón",
    "Colonia Santa María",
    "Colonia Santa Teresa",
    "Conhelo",
    "Coronel Hilario Lagos",
    "Cuchillo Co",
    "Doblas",
    "Dorila",
    "Eduardo Castex",
    "Embajador Martini",
    "Falucho",
    "General Acha",
    "General Campos",
    "General Pico",
    "General San Martín",
    "Gobernador Duval",
    "Guatraché",
    "Ingeniero Luiggi",
    "Intendente Alvear",
    "Jacinto Aráuz",
    "La Adela",
    "La Humada",
    "La Maruja",
    "La Reforma",
    "Limay Mahuida",
    "Lonquimay",
    "Loventué",
    "Luan Toro",
    "Macachín",
    "Maisonave",
    "Mauricio Mayer",
    "Metileo",
    "Miguel Cané",
    "Miguel Riglos",
    "Monte Nievas",
    "Parera",
    "Perú",
    "Pichi Huinca",
    "Puelches",
    "Puelén",
    "Quehué",
    "Quemú Quemú",
    "Quetrequén",
    "Rancul",
    "Realicó",
    "Relmo",
    "Rolón",
    "Rucanelo",
    "Santa Isabel",
    "Santa Rosa",
    "Sarah",
    "Speluzzi",
    "Telén",
    "Toay",
    "Tomás M. Anchorena",
    "Trenel",
    "Unanué",
    "Uriburu",
    "Vértiz",
    "Victorica",
    "Villa Mirasol",
    "Winifreda",
  ],
  LA_RIOJA: [
    "Ángel Vicente Peñaloza",
    "Arauco",
    "Castro Barros",
    "Chamical",
    "Chilecito",
    "Famatina",
    "General Belgrano",
    "General Felipe Varela",
    "General Juan Facundo Quiroga",
    "General Lamadrid",
    "General Ortiz de Ocampo",
    "General San Martín",
    "Independencia",
    "La Rioja",
    "Rosario Vera Peñaloza",
    "San Blas de Los Sauces",
    "Sanagasta",
    "Vinchina",
  ],
  MENDOZA: [
    "General Alvear",
    "Godoy Cruz",
    "Guaymallén",
    "Junín",
    "La Paz",
    "Las Heras",
    "Lavalle",
    "Luján de Cuyo",
    "Maipú",
    "Malargüe",
    "Mendoza",
    "Rivadavia",
    "San Carlos",
    "San Martín",
    "San Rafael",
    "Santa Rosa",
    "Tunuyán",
    "Tupungato",
  ],
  MISIONES: [
    "25 de Mayo",
    "9 de Julio",
    "Alba Posse",
    "Almafuerte",
    "Apóstoles",
    "Aristóbulo del Valle",
    "Arroyo del Medio",
    "Azara",
    "Bernardo de Irigoyen",
    "Bonpland",
    "Caá Yarí",
    "Campo Grande",
    "Campo Ramón",
    "Campo Viera",
    "Candelaria",
    "Capioví",
    "Caraguatay",
    "Cerro Azul",
    "Cerro Corá",
    "Colonia Alberdi",
    "Colonia Aurora",
    "Colonia Delicia",
    "Colonia Polana",
    "Colonia Victoria",
    "Colonia Wanda",
    "Comandante Andresito",
    "Concepción de la Sierra",
    "Corpus Christi",
    "Dos Arroyos",
    "Dos de Mayo",
    "El Alcázar",
    "El Soberbio",
    "Eldorado",
    "Fachinal",
    "Florentino Ameghino",
    "Garuhapé",
    "Garupá",
    "General Alvear",
    "General Urquiza",
    "Gobernador López",
    "Gobernador Roca",
    "Guaraní",
    "Hipólito Yrigoyen",
    "Itacaruaré",
    "Jardín América",
    "Leandro N. Alem",
    "Libertad",
    "Loreto",
    "Los Helechos",
    "Mártires",
    "Mojón Grande",
    "Montecarlo",
    "Oberá",
    "Olegario V. Andrade",
    "Panambí",
    "Posadas",
    "Pozo Azul",
    "Profundidad",
    "Puerto Esperanza",
    "Puerto Iguazú",
    "Puerto Leoni",
    "Puerto Piray",
    "Puerto Rico",
    "Ruiz de Montoya",
    "San Antonio",
    "San Ignacio",
    "San Javier",
    "San José",
    "San Martín",
    "San Pedro",
    "San Vicente",
    "Santa Ana",
    "Santa María",
    "Santiago de Liniers",
    "Santo Pipó",
    "Tres Capones",
  ],
  NEUQUEN: [
    "Aguada San Roque",
    "Aluminé",
    "Andacollo",
    "Añelo",
    "Bajada del Agrio",
    "Barrancas",
    "Buta Ranquil",
    "Caviahue - Copahue",
    "Centenario",
    "Chorriaca",
    "Chos Malal",
    "Covunco Abajo",
    "Coyuco - Cochico",
    "Cutral Co",
    "El Cholar",
    "El Huecú",
    "El Sauce",
    "Guañacos",
    "Huinganco",
    "Junín de los Andes",
    "Las Coloradas",
    "Las Lajas",
    "Las Ovejas",
    "Loncopué",
    "Los Catutos",
    "Los Chihuidos",
    "Los Miches",
    "Manzano Amargo",
    "Mariano Moreno",
    "Neuquén",
    "Octavio Pico",
    "Paso Aguerre",
    "Picún Leufú",
    "Piedra del Águila",
    "Pilo Lil",
    "Plaza Huincul",
    "Plottier",
    "Quili Malal",
    "Ramón M. Castro",
    "Rincón de los Sauces",
    "San Martín de los Andes",
    "San Patricio del Chañar",
    "Santo Tomás",
    "Sauzal Bonito",
    "Senillosa",
    "Taquimilán",
    "Tricao Malal",
    "Varvarco - Invernada Vieja",
    "Villa Curi Leuvú",
    "Villa del Nahueve",
    "Villa El Chocón",
    "Villa La Angostura",
    "Villa Pehuenia",
    "Villa Puente Picún Leufú",
    "Villa Traful",
    "Vista Alegre",
    "Zapala",
  ],
  RIO_NEGRO: [
    "Allen",
    "Campo Grande",
    "Catriel",
    "Cervantes",
    "Chichinales",
    "Chimpay",
    "Choele Choel",
    "Cinco Saltos",
    "Cipolletti",
    "Comallo",
    "Contralmirante Cordero",
    "Coronel Belisle",
    "Darwin",
    "Dina Huapi",
    "El Bolsón",
    "General Conesa",
    "General Enrique Godoy",
    "General Fernández Oro",
    "General Roca",
    "Guardia Mitre",
    "Ingeniero Huergo",
    "Ingeniero Jacobacci",
    "Lamarque",
    "Los Menucos",
    "Luis Beltrán",
    "Mainqué",
    "Maquinchao",
    "Ministro Ramos Mexía",
    "Ñorquinco",
    "Pilcaniyeu",
    "Pomona",
    "Río Colorado",
    "San Antonio Oeste",
    "San Carlos de Bariloche",
    "Sierra Colorada",
    "Sierra Grande",
    "Valcheta",
    "Viedma",
    "Villa Regina",
  ],
  SALTA: [
    "Aguaray",
    "Aguas Blancas",
    "Angastaco",
    "Animaná",
    "Apolinario Saravia",
    "Cachi",
    "Cafayate",
    "Campo Quijano",
    "Campo Santo",
    "Chicoana",
    "Colonia Santa Rosa",
    "Coronel Moldes",
    "El Bordo",
    "El Carril",
    "El Galpón",
    "El Jardín",
    "El Potrero",
    "El Quebrachal",
    "El Tala",
    "Embarcación",
    "General Ballivián",
    "General Güemes",
    "General Mosconi",
    "General Pizarro",
    "Guachipas",
    "Hipólito Yrigoyen",
    "Iruya",
    "Isla de Cañas",
    "Joaquín V. González",
    "La Caldera",
    "La Candelaria",
    "La Merced",
    "La Poma",
    "La Viña",
    "Las Lajitas",
    "Los Toldos",
    "Molinos",
    "Nazareno",
    "Payogasta",
    "Pichanal",
    "Profesor Salvador Mazza",
    "Río Piedras",
    "Rivadavia Banda Norte",
    "Rivadavia Banda Sur",
    "Rosario de la Frontera",
    "Rosario de Lerma",
    "Salta",
    "San Antonio de los Cobres",
    "San Carlos",
    "San José de los Cerrillos",
    "San José de Metán",
    "San Lorenzo",
    "San Ramón de la Nueva Orán",
    "Santa Victoria Este",
    "Santa Victoria Oeste",
    "Seclantás",
    "Tartagal",
    "Tolar Grande",
    "Urundel",
    "Vaqueros",
  ],
  SAN_JUAN: [
    "25 de Mayo",
    "9 de Julio",
    "Albardón",
    "Angaco",
    "Calingasta",
    "Caucete",
    "Chimbas",
    "Iglesia",
    "Jáchal",
    "Pocito",
    "Rawson",
    "Rivadavia",
    "San Juan",
    "San Martín",
    "Santa Lucía",
    "Sarmiento",
    "Ullum",
    "Valle Fértil",
    "Zonda",
  ],
  SAN_LUIS: [
    "Alto Pelado",
    "Alto Pencoso",
    "Anchorena",
    "Arizona",
    "Bagual",
    "Balde",
    "Batavia",
    "Beazley",
    "Buena Esperanza",
    "Candelaria",
    "Carpintería",
    "Concarán",
    "Cortaderas",
    "Desaguadero",
    "El Trapiche",
    "El Volcán",
    "Estancia Grande",
    "Fortín El Patria",
    "Fortuna",
    "Fraga",
    "Juan Jorba",
    "Juan Llerena",
    "Juana Koslay",
    "Justo Daract",
    "La Calera",
    "La Carolina",
    "La Punilla",
    "La Punta",
    "La Toma",
    "La Vertiente",
    "Lafinur",
    "Las Aguadas",
    "Las Chacras",
    "Las Lagunas",
    "Lavaisse",
    "Leandro N. Alem",
    "Los Manantiales",
    "Los Molles",
    "Luján",
    "Nación Ranquel",
    "Naschel",
    "Navia",
    "Nogolí",
    "Nueva Galia",
    "Papagayos",
    "Paso Grande",
    "Potrero de los Funes",
    "Quines",
    "Renca",
    "Saladillo",
    "San Francisco",
    "San Jerónimo",
    "San José del Morro",
    "San Luis",
    "San Martín",
    "San Pablo",
    "Santa Rosa",
    "Talita",
    "Tilisarao",
    "Unión",
    "Villa de la Quebrada",
    "Villa de Merlo",
    "Villa de Praga",
    "Villa del Carmen",
    "Villa Larca",
    "Villa Mercedes",
    "Zanjitas",
  ],
  SANTA_CRUZ: [
    "28 de Noviembre",
    "Bajo Caracoles",
    "Caleta Olivia",
    "Cañadón Seco",
    "Comandante Luis Piedrabuena",
    "El Calafate",
    "El Chaltén",
    "El Turbio",
    "Fitz Roy",
    "Gobernador Gregores",
    "Hipólito Yrigoyen",
    "Jaramillo",
    "Julia Dufour",
    "Koluel Kaike",
    "Las Heras",
    "Los Antiguos",
    "Perito Moreno",
    "Pico Truncado",
    "Puerto Deseado",
    "Puerto San Julián",
    "Puerto Santa Cruz",
    "Río Gallegos",
    "Rospentek",
    "Tellier",
    "Tres Lagos",
    "Yacimientos Río Turbio",
  ],
  SANTA_FE: [
    "Aarón Castellanos",
    "Acebal",
    "Aguará Grande",
    "Albarellos",
    "Alcorta",
    "Aldao",
    "Alejandra",
    "Álvarez",
    "Alvear",
    "Ambrosetti",
    "Amenábar",
    "Angélica",
    "Angeloni",
    "Arequito",
    "Arminda",
    "Armstrong",
    "Arocena",
    "Arroyo Aguiar",
    "Arroyo Ceibal",
    "Arroyo Leyes",
    "Arroyo Seco",
    "Arrufo",
    "Arteaga",
    "Ataliva",
    "Aurelia",
    "Avellaneda",
    "Barrancas",
    "Bauer y Sigel",
    "Bella Italia",
    "Berabevú",
    "Berna",
    "Bernardo de Irigoyen",
    "Bigand",
    "Bombal",
    "Bouquet",
    "Bustinza",
    "Cabal",
    "Cacique Ariacaiquín",
    "Cafferata",
    "Calchaquí",
    "Campo Andino",
    "Campo Piaggio",
    "Candioti",
    "Cañada de Gómez",
    "Cañada del Ucle",
    "Cañada Ombú",
    "Cañada Rica",
    "Cañada Rosquín",
    "Capitán Bermúdez",
    "Capivara",
    "Carcarañá",
    "Carlos Pellegrini",
    "Carmen",
    "Carmen del Sauce",
    "Carreras",
    "Carrizales",
    "Casalegno",
    "Casas",
    "Casilda",
    "Castelar",
    "Castellanos",
    "Cavour",
    "Cayastá",
    "Cayastacito",
    "Centeno",
    "Cepeda",
    "Ceres",
    "Chabas",
    "Chañar Ladeado",
    "Chapuy",
    "Chovet",
    "Christophersen",
    "Classon",
    "Colonia Aldao",
    "Colonia Ana",
    "Colonia Belgrano",
    "Colonia Bicha",
    "Colonia Bigand",
    "Colonia Bossi",
    "Colonia Cello",
    "Colonia Clara",
    "Colonia Dolores",
    "Colonia Durán",
    "Colonia Iturraspe",
    "Colonia Margarita",
    "Colonia Mascías",
    "Colonia Maua",
    "Colonia Raquel",
    "Colonia Rosa",
    "Constanza",
    "Coronda",
    "Coronel Arnold",
    "Coronel Bogado",
    "Coronel Domínguez",
    "Coronel Fraga",
    "Correa",
    "Crispi",
    "Cululú",
    "Curupaity",
    "Desvío Arijón",
    "Díaz",
    "Diego de Alvear",
    "Dos Rosas y La Legua",
    "Egusquiza",
    "El Araza",
    "El Rabón",
    "El Sombrerito",
    "El Trébol",
    "Elisa",
    "Elortondo",
    "Emilia",
    "Empalme San Carlos",
    "Empalme Villa Constitución",
    "Esmeralda",
    "Esperanza",
    "Estación Clucellas",
    "Esteban Rams",
    "Esther",
    "Eusebia y Carolina",
    "Eustolia",
    "Felicia",
    "Fidela",
    "Fighiera",
    "Firmat",
    "Florencia",
    "Fortín Olmos",
    "Franck",
    "Fray Luis Beltrán",
    "Frontera",
    "Fuentes",
    "Funes",
    "Gaboto",
    "Galisteo",
    "Gálvez",
    "Garabato",
    "Garibaldi",
    "Gato Colorado",
    "General Gelly",
    "General Lagos",
    "Gessler",
    "Gobernador Crespo",
    "Gödeken",
    "Godoy",
    "Golondrina",
    "Granadero Baigorria",
    "Gregoria Pérez de Denis",
    "Grutly",
    "Guadalupe Norte",
    "Helvecia",
    "Hersilia",
    "Hipatía",
    "Huanqueros",
    "Hugentobler",
    "Hughes",
    "Humberto Primo",
    "Humboldt",
    "Ibarlucea",
    "Ingeniero Chanourdie",
    "Intiyaco",
    "Irigoyen",
    "Ituzaingó",
    "Jacinto L. Aráuz",
    "Josefina",
    "Juan B. Molina",
    "Juan de Garay",
    "Juncal",
    "La Brava",
    "La Cabral",
    "La Camila",
    "La Chispa",
    "La Criolla",
    "La Gallareta",
    "La Lucila",
    "La Pelada",
    "La Penca y Caraguatá",
    "La Rubia",
    "La Sarita",
    "La Vanguardia",
    "Labordeboy",
    "Laguna Paiva",
    "Landeta",
    "Lanteri",
    "Larrechea",
    "Las Avispas",
    "Las Bandurrias",
    "Las Garzas",
    "Las Palmeras",
    "Las Parejas",
    "Las Petacas",
    "Las Rosas",
    "Las Toscas",
    "Las Tunas",
    "Lazzarino",
    "Lehmann",
    "Llambí Campbell",
    "Logroño",
    "Loma Alta",
    "López",
    "Los Amores",
    "Los Cardos",
    "Los Laureles",
    "Los Molinos",
    "Los Quirquinchos",
    "Los Tábanos",
    "Lucio V. López",
    "Luis Palacios",
    "Maciel",
    "Maggiolo",
    "Malabrigo",
    "Marcelino Escalada",
    "Margarita",
    "María Juana",
    "María Luisa",
    "María Susana",
    "María Teresa",
    "Matilde",
    "Máximo Paz",
    "Melincué",
    "Miguel Torres",
    "Moisés Ville",
    "Monigotes",
    "Monje",
    "Monte Oscuridad",
    "Monte Vera",
    "Montefiore",
    "Montes de Oca",
    "Murphy",
    "Naré",
    "Nelson",
    "Nicanor Molinas",
    "Nuevo Torino",
    "Ñanducita",
    "Oliveros",
    "Palacios",
    "Pavón",
    "Pavón Arriba",
    "Pedro Gómez Cello",
    "Pérez",
    "Peyrano",
    "Piamonte",
    "Pilar",
    "Piñero",
    "Plaza Clucellas",
    "Portugalete",
    "Pozo Borrado",
    "Presidente Roca",
    "Progreso",
    "Providencia",
    "Pueblo Andino",
    "Pueblo Esther",
    "Pueblo Marini",
    "Pueblo Muñoz",
    "Puerto General San Martín",
    "Pujato",
    "Pujato Norte",
    "Rafaela",
    "Ramayón",
    "Ramona",
    "Reconquista",
    "Recreo",
    "Ricardone",
    "Rivadavia",
    "Roldán",
    "Romang",
    "Rosario",
    "Rueda",
    "Rufino",
    "Sa Pereyra",
    "Saguier",
    "Saladero Mariano Cabal",
    "Salto Grande",
    "San Agustín",
    "San Antonio",
    "San Antonio de Obligado",
    "San Bernardo",
    "San Carlos Centro",
    "San Carlos Norte",
    "San Carlos Sud",
    "San Cristóbal",
    "San Eduardo",
    "San Eugenio",
    "San Fabián",
    "San Francisco de Santa Fe",
    "San Genaro",
    "San Gregorio",
    "San Guillermo",
    "San Javier",
    "San Jerónimo del Sauce",
    "San Jerónimo Norte",
    "San Jerónimo Sud",
    "San Jorge",
    "San José",
    "San José de la Esquina",
    "San José del Rincón",
    "San Justo",
    "San Lorenzo",
    "San Mariano",
    "San Martín de las Escobas",
    "San Martín Norte",
    "San Vicente",
    "Sancti Spiritu",
    "Sanford",
    "Santa Clara de Buena Vista",
    "Santa Clara de Saguier",
    "Santa Fe",
    "Santa Isabel",
    "Santa Margarita",
    "Santa María Centro",
    "Santa María Norte",
    "Santa Rosa de Calchines",
    "Santa Teresa",
    "Santo Domingo",
    "Santo Tomé",
    "Santurce",
    "Sargento Cabral",
    "Sarmiento",
    "Sastre y Ortiz",
    "Sauce Viejo",
    "Serodino",
    "Silva",
    "Soldini",
    "Soledad",
    "Soutomayor",
    "Suardi",
    "Sunchales",
    "Susana",
    "Tacuarendi",
    "Tacural",
    "Tacurales",
    "Tartagal",
    "Teodelina",
    "Theobald",
    "Timbúes",
    "Toba",
    "Tortugas",
    "Tostado",
    "Totoras",
    "Traill",
    "Uranga",
    "Venado Tuerto",
    "Vera",
    "Vera y Pintado",
    "Videla",
    "Vila",
    "Villa Amelia",
    "Villa Ana",
    "Villa Cañás",
    "Villa Constitución",
    "Villa Eloísa",
    "Villa Gobernador Gálvez",
    "Villa Guillermina",
    "Villa Minetti",
    "Villa Mugueta",
    "Villa Ocampo",
    "Villa San José",
    "Villa Saralegui",
    "Villa Trinidad",
    "Villada",
    "Virginia",
    "Wheelwright",
    "Zavalla",
    "Zenón Pereyra",
  ],
  SANTIAGO_DEL_ESTERO: [
    "Abra Grande",
    "Aerolito",
    "Alhuampa",
    "Ancaján",
    "Antajé",
    "Añatuya",
    "Ardiles",
    "Argentina",
    "Árraga",
    "Averías",
    "Bandera",
    "Bandera Bajada",
    "Beltrán",
    "Brea Pozo",
    "Campo Gallo",
    "Cañada Escobar",
    "Casares",
    "Caspi Corral",
    "Chauchillas",
    "Chaupi Pozo",
    "Chilca Juliana",
    "Choya",
    "Clodomira",
    "Colonia Alpina",
    "Colonia Dora",
    "Colonia El Simbolar",
    "Colonia San Juan",
    "Colonia Tinco",
    "Coronel Manuel L. Rico",
    "Cuatro Bocas",
    "Donadeu",
    "El 49",
    "El Arenal",
    "El Bobadal",
    "El Caburé",
    "El Charco",
    "El Colorado",
    "El Crucero",
    "El Cuadrado",
    "El Deán",
    "El Mojón",
    "El Rincón",
    "El Sauzal",
    "El Zanjón",
    "Estación Atamisqui",
    "Estación La Punta",
    "Estación Robles",
    "Estación Taboada",
    "Estación Tacañitas",
    "Fernández",
    "Fortín Inca",
    "Frías",
    "Garza",
    "Gramilla",
    "Guardia Escolta",
    "Hasse",
    "Hernán Mejía Miraval",
    "Herrera",
    "Huyamampa",
    "Icaño",
    "Ingeniero Forres",
    "Isca Yacu",
    "Isca Yacu Semaul",
    "La Aurora",
    "La Banda",
    "La Cañada",
    "La Dársena",
    "La Invernada",
    "La Nena",
    "La Nueva Donosa",
    "Laprida",
    "Las Delicias",
    "Las Tinajas",
    "Lavalle",
    "Libertad",
    "Lilo Viejo",
    "Los Cardozos",
    "Los Juríes",
    "Los Miranda",
    "Los Núñez",
    "Los Pirpintos",
    "Los Quiroga",
    "Los Soria",
    "Los Telares",
    "Los Tigres",
    "Lugones",
    "Maco",
    "Malbrán",
    "Mansupa",
    "Maquito",
    "Matará",
    "Medellín",
    "Minerva",
    "Monte Quemado",
    "Morales",
    "Nueva Esperanza",
    "Nueva Francia",
    "Palo Negro",
    "Pampa de los Guanacos",
    "Patay",
    "Pozo Betbeder",
    "Pozo Hondo",
    "Pozuelos",
    "Pueblo Pablo Torelo",
    "Puesto de San Antonio",
    "Quimili",
    "Ramírez de Velazco",
    "Rapelli",
    "Real Sayana",
    "Rodeo de Valdez",
    "Roversi",
    "Sachayoj",
    "San José del Boquerón",
    "San Pedro",
    "Santa María",
    "Santiago del Estero",
    "Santo Domingo",
    "Santos Lugares",
    "Selva",
    "Simbol",
    "Simbolar",
    "Sol de Julio",
    "Sumamao",
    "Sumampa",
    "Sumampa Viejo",
    "Suncho Corral",
    "Tapso",
    "Termas de Río Hondo",
    "Tintina",
    "Tomás Young",
    "Tramo 16",
    "Tramo 20",
    "Urutaú",
    "Vaca Huañuna",
    "Vilelas",
    "Villa Atamisqui",
    "Villa Figueroa",
    "Villa General Mitre",
    "Villa Giménez",
    "Villa La Punta",
    "Villa Mailín",
    "Villa Nueva",
    "Villa Ojo de Agua",
    "Villa Río Hondo",
    "Villa Salavina",
    "Villa San Martín (Est. Loreto)",
    "Villa Silípica",
    "Villa Unión",
    "Vilmer",
    "Vinará",
    "Vuelta de la Barranca",
    "Weisburd",
    "Yanda",
    "Yuchán",
  ],
  TIERRA_DEL_FUEGO: [
    "Río Grande",
    "Tolhuin",
    "Ushuaia",
  ],
  TUCUMAN: [
    "7 de Abril",
    "Acheral",
    "Agua Dulce y La Soledad",
    "Aguilares",
    "Alderetes",
    "Alpachiri y El Molino",
    "Alto Verde y Los Guchea",
    "Amaicha del Valle",
    "Amberes",
    "Anca Juli",
    "Arcadia",
    "Atahona",
    "Banda del Río Salí",
    "Bella Vista",
    "Benjamín Aráoz y El Tajamar",
    "Buena Vista",
    "Burruyacú",
    "Capitán Cáceres",
    "Cevil Redondo",
    "Choromoro",
    "Ciudacita",
    "Colalao del Valle",
    "Colombres",
    "Concepción",
    "Delfín Gallo",
    "El Bracho y El Cevilar",
    "El Cadillal",
    "El Cercado",
    "El Chañar",
    "El Manantial",
    "El Mojón",
    "El Mollar",
    "El Naranjito",
    "El Naranjo y El Sunchal",
    "El Polear y Los Córdoba",
    "El Puestito",
    "El Sacrificio",
    "El Timbó",
    "Escaba",
    "Esquina y Mancopa",
    "Estación Aráoz y Tacanas",
    "Famaillá",
    "Garmendia",
    "Gastona y Belicha",
    "Gobernador Piedrabuena",
    "Graneros",
    "Huasa Pampa",
    "Juan Bautista Alberdi",
    "La Cocha",
    "La Esperanza",
    "La Florida y Luisiana",
    "La Ramada y La Cruz",
    "La Trinidad",
    "Lamadrid",
    "Las Cejas",
    "Las Talas",
    "Las Talitas",
    "León Rouges y Santa Rosa",
    "Los Bulacio y Los Villagra",
    "Los Gómez",
    "Los Nogales",
    "Los Pereyra",
    "Los Pérez",
    "Los Puestos",
    "Los Ralos",
    "Los Sarmiento y La Tipa",
    "Los Sosa",
    "Manuel García Fernández",
    "Manuela Pedraza",
    "Medina",
    "Monte Bello",
    "Monteagudo",
    "Monteros",
    "Pampa Mayo",
    "Quilmes y Los Sueldos",
    "Raco",
    "Ranchillos y San Miguel",
    "Río Chico y Nueva Trinidad",
    "Río Colorado",
    "Río Seco",
    "Rumi Punco",
    "San Andrés",
    "San Felipe y Santa Bárbara",
    "San Ignacio",
    "San Isidro de Lules",
    "San Javier",
    "San José de la Cocha",
    "San Miguel de Tucumán",
    "San Pablo y Villa Nougués",
    "San Pedro de Colalao",
    "San Pedro y San Antonio",
    "Santa Ana",
    "Santa Cruz y La Tuna",
    "Santa Lucía",
    "Santa Rosa de Leales y Laguna Blanca",
    "Sargento Moya",
    "Simoca",
    "Soldado Maldonado",
    "Taco Ralo",
    "Tafí del Valle",
    "Tafí Viejo",
    "Tapia",
    "Teniente Berdina",
    "Trancas",
    "Villa Belgrano",
    "Villa Chicligasta",
    "Villa de Leales",
    "Villa Padre Monti",
    "Villa Quinteros",
    "Yánima y El Corralito",
    "Yerba Buena",
  ],
};
